namespace: ai_one
base_dir: ./datastore

profile:
  name: small
  ram_limit_mb: 512
  max_symbols_hot: 96
  hot_ttl_sec: 21600      # 6h
  warm_ttl_sec: 86400     # 24h
  flush_batch_max: 8
  flush_queue_soft: 200
  flush_queue_hard: 1000

intervals_ttl:
  "1m": 21600             # 6h
  "5m": 43200             # 12h
  "15m": 86400
  "1h": 259200            # 3d
  "4h": 604800            # 7d
  "1d": 2592000           # 30d

write_behind: true
validate_on_write: true
validate_on_read: true

io_retry_attempts: 3
io_retry_backoff: 0.25

admin:
  # вмикає командний канал для живого керування (через redis pubsub)
  commands_channel: ai_one:admin:commands
  # раз у N секунд робити короткий health ping у логи/метрики
  health_ping_sec: 30

trade_updater:
  skipped_ewma_alpha: 0.3
  backoff_multiplier: 1.5
  max_backoff_sec: 300
  drift_warn_high: 2.5
  drift_warn_low: 0.5
  pressure_warn: 2.0
  cycle_histogram_buckets: [0.1,0.25,0.5,1,2,5,10,30,60,120,300]
  auto_interval_scale_enabled: true
  auto_interval_scale_cycles: 3
  auto_interval_scale_factor: 1.3
  auto_interval_scale_cap: 600
  auto_alpha_enabled: true
  alpha_min: 0.05
  alpha_max: 0.6
  alpha_step: 0.05
  alpha_turbulence_drift: 2.0
  alpha_turbulence_pressure: 1.5
  alpha_calm_drift: 1.05
  alpha_calm_pressure: 0.5
  alpha_calm_cycles: 5
  publish_skip_reasons: true
  skip_reasons_top_n: 5
  dynamic_priority_enabled: false
  dynamic_priority_min_active: 10