# ruff: noqa: N999
# Порогові значення підібрано з урахуванням типу активу та його волатильності.
# Мега-коригування (BTC, ETH) мають нижчі пороги (RSI ~70/30,
# невисокий vol_z) через стабільніші обсяги.
# Мем-коїни (DOGE, SHIB, PEPE, FLOKI тощо) отримали ширші межі (RSI ~80/20)
# і вищий vol_z_threshold, оскільки їх обсяги та ціни сильно коливаються.
# Активи середньої капіталізації налаштовано на середні значення
# (RSI ~75/25, vol_z ~2.5σ), а дрібні та схильні до маніпуляцій токени –
# на найбільші пороги для фільтрації шумів.


from __future__ import annotations

from typing import Any


def get_top100_threshold(symbol: str) -> dict[str, Any] | None:
    """Повертає мапу дефолтних порогів для конкретного символу (Top100),
    сумісну з Thresholds.from_mapping.

    Примітки:
      - В цьому модулі конфіг має ключі типу vol_z_threshold, rsi_overbought/oversold,
        додатково atr_pct_min, vwap_deviation (які не обов'язкові для Thresholds).
      - Ми приводимо до очікуваних ключів: volume_z_threshold, rsi_*; додаємо базові
        low_gate/high_gate/atr_target, якщо не задані.
    """
    try:
        if not symbol or not isinstance(symbol, str):
            return None
        sym_l = symbol.lower()
        cfg = TOP100_THRESHOLDS.get(sym_l)
        if not cfg:
            return None
        # Базові загальні значення (можете скоригувати під актив при потребі)
        mapping = {
            "symbol": symbol.upper(),
            "low_gate": 0.006,
            "high_gate": 0.015,
            "atr_target": 0.5,
        }
        # Перенесення ключів у канонічний формат
        if "vol_z_threshold" in cfg:
            mapping["volume_z_threshold"] = cfg.get("vol_z_threshold")
        if "rsi_overbought" in cfg:
            mapping["rsi_overbought"] = cfg.get("rsi_overbought")
        if "rsi_oversold" in cfg:
            mapping["rsi_oversold"] = cfg.get("rsi_oversold")
        # За потреби можна використати atr_pct_min/vwap_deviation для похідних порогів
        return mapping
    except Exception:
        return None


TOP100_THRESHOLDS: dict[str, dict[str, float]] = {
    "btcusdt": {
        "vol_z_threshold": 2.0,
        "rsi_overbought": 70.0,
        "rsi_oversold": 30.0,
        "atr_pct_min": 0.005,
        "vwap_deviation": 0.01,
    },
    "ethusdt": {
        "vol_z_threshold": 2.0,
        "rsi_overbought": 70.0,
        "rsi_oversold": 30.0,
        "atr_pct_min": 0.005,
        "vwap_deviation": 0.01,
    },
    "solusdt": {
        "vol_z_threshold": 2.5,
        "rsi_overbought": 80.0,
        "rsi_oversold": 20.0,
        "atr_pct_min": 0.008,
        "vwap_deviation": 0.02,
    },
    "dogeusdt": {
        "vol_z_threshold": 3.0,
        "rsi_overbought": 80.0,
        "rsi_oversold": 20.0,
        "atr_pct_min": 0.010,
        "vwap_deviation": 0.04,
    },
    "xrpusdt": {
        "vol_z_threshold": 2.5,
        "rsi_overbought": 80.0,
        "rsi_oversold": 20.0,
        "atr_pct_min": 0.008,
        "vwap_deviation": 0.03,
    },
    "bnbusdt": {
        "vol_z_threshold": 2.5,
        "rsi_overbought": 75.0,
        "rsi_oversold": 25.0,
        "atr_pct_min": 0.007,
        "vwap_deviation": 0.02,
    },
    "1000shibusdt": {
        "vol_z_threshold": 3.0,
        "rsi_overbought": 80.0,
        "rsi_oversold": 20.0,
        "atr_pct_min": 0.015,
        "vwap_deviation": 0.05,
    },
    "adausdt": {
        "vol_z_threshold": 2.5,
        "rsi_overbought": 75.0,
        "rsi_oversold": 25.0,
        "atr_pct_min": 0.007,
        "vwap_deviation": 0.02,
    },
    "trxusdt": {
        "vol_z_threshold": 2.5,
        "rsi_overbought": 72.0,
        "rsi_oversold": 28.0,
        "atr_pct_min": 0.006,
        "vwap_deviation": 0.02,
    },
    "maticusdt": {
        "vol_z_threshold": 2.5,
        "rsi_overbought": 75.0,
        "rsi_oversold": 25.0,
        "atr_pct_min": 0.007,
        "vwap_deviation": 0.02,
    },
    "avaxusdt": {
        "vol_z_threshold": 2.5,
        "rsi_overbought": 75.0,
        "rsi_oversold": 25.0,
        "atr_pct_min": 0.008,
        "vwap_deviation": 0.02,
    },
    "linkusdt": {
        "vol_z_threshold": 2.5,
        "rsi_overbought": 78.0,
        "rsi_oversold": 22.0,
        "atr_pct_min": 0.008,
        "vwap_deviation": 0.02,
    },
    "suiusdt": {
        "vol_z_threshold": 2.5,
        "rsi_overbought": 75.0,
        "rsi_oversold": 25.0,
        "atr_pct_min": 0.008,
        "vwap_deviation": 0.02,
    },
    "tonusdt": {
        "vol_z_threshold": 2.5,
        "rsi_overbought": 72.0,
        "rsi_oversold": 28.0,
        "atr_pct_min": 0.007,
        "vwap_deviation": 0.02,
    },
    "nearusdt": {
        "vol_z_threshold": 2.5,
        "rsi_overbought": 75.0,
        "rsi_oversold": 25.0,
        "atr_pct_min": 0.007,
        "vwap_deviation": 0.02,
    },
    "bchusdt": {
        "vol_z_threshold": 3.0,
        "rsi_overbought": 78.0,
        "rsi_oversold": 22.0,
        "atr_pct_min": 0.010,
        "vwap_deviation": 0.03,
    },
    "opusdt": {
        "vol_z_threshold": 2.5,
        "rsi_overbought": 75.0,
        "rsi_oversold": 25.0,
        "atr_pct_min": 0.008,
        "vwap_deviation": 0.02,
    },
    "arbusdt": {
        "vol_z_threshold": 2.5,
        "rsi_overbought": 75.0,
        "rsi_oversold": 25.0,
        "atr_pct_min": 0.008,
        "vwap_deviation": 0.02,
    },
    "1000pepeusdt": {
        "vol_z_threshold": 3.0,
        "rsi_overbought": 85.0,
        "rsi_oversold": 15.0,
        "atr_pct_min": 0.015,
        "vwap_deviation": 0.05,
    },
    "1000flokusdt": {
        "vol_z_threshold": 3.0,
        "rsi_overbought": 85.0,
        "rsi_oversold": 15.0,
        "atr_pct_min": 0.015,
        "vwap_deviation": 0.05,
    },
    "atomusdt": {
        "vol_z_threshold": 2.5,
        "rsi_overbought": 73.0,
        "rsi_oversold": 27.0,
        "atr_pct_min": 0.007,
        "vwap_deviation": 0.02,
    },
    "ltcusdt": {
        "vol_z_threshold": 2.5,
        "rsi_overbought": 70.0,
        "rsi_oversold": 30.0,
        "atr_pct_min": 0.006,
        "vwap_deviation": 0.02,
    },
    "xlmusdt": {
        "vol_z_threshold": 2.5,
        "rsi_overbought": 78.0,
        "rsi_oversold": 22.0,
        "atr_pct_min": 0.008,
        "vwap_deviation": 0.02,
    },
    "filusdt": {
        "vol_z_threshold": 2.5,
        "rsi_overbought": 75.0,
        "rsi_oversold": 25.0,
        "atr_pct_min": 0.008,
        "vwap_deviation": 0.02,
    },
    "uniusdt": {
        "vol_z_threshold": 2.5,
        "rsi_overbought": 74.0,
        "rsi_oversold": 23.0,
        "atr_pct_min": 0.007,
        "vwap_deviation": 0.02,
    },
    "aaveusdt": {
        "vol_z_threshold": 2.5,
        "rsi_overbought": 74.0,
        "rsi_oversold": 23.0,
        "atr_pct_min": 0.007,
        "vwap_deviation": 0.02,
    },
    "hbarusdt": {
        "vol_z_threshold": 2.5,
        "rsi_overbought": 75.0,
        "rsi_oversold": 25.0,
        "atr_pct_min": 0.008,
        "vwap_deviation": 0.02,
    },
    "dotusdt": {
        "vol_z_threshold": 2.5,
        "rsi_overbought": 74.0,
        "rsi_oversold": 24.0,
        "atr_pct_min": 0.007,
        "vwap_deviation": 0.02,
    },
    "manausdt": {
        "vol_z_threshold": 2.5,
        "rsi_overbought": 76.0,
        "rsi_oversold": 24.0,
        "atr_pct_min": 0.008,
        "vwap_deviation": 0.03,
    },
    "sandusdt": {
        "vol_z_threshold": 2.5,
        "rsi_overbought": 76.0,
        "rsi_oversold": 24.0,
        "atr_pct_min": 0.008,
        "vwap_deviation": 0.03,
    },
    "rndrusdt": {
        "vol_z_threshold": 2.5,
        "rsi_overbought": 77.0,
        "rsi_oversold": 23.0,
        "atr_pct_min": 0.009,
        "vwap_deviation": 0.03,
    },
    "egldusdt": {
        "vol_z_threshold": 2.5,
        "rsi_overbought": 75.0,
        "rsi_oversold": 25.0,
        "atr_pct_min": 0.009,
        "vwap_deviation": 0.03,
    },
    "twtusdt": {
        "vol_z_threshold": 3.0,
        "rsi_overbought": 80.0,
        "rsi_oversold": 20.0,
        "atr_pct_min": 0.012,
        "vwap_deviation": 0.04,
    },
    "injusdt": {
        "vol_z_threshold": 2.5,
        "rsi_overbought": 77.0,
        "rsi_oversold": 23.0,
        "atr_pct_min": 0.009,
        "vwap_deviation": 0.03,
    },
    "dydxusdt": {
        "vol_z_threshold": 2.5,
        "rsi_overbought": 77.0,
        "rsi_oversold": 23.0,
        "atr_pct_min": 0.009,
        "vwap_deviation": 0.03,
    },
    "wldusdt": {
        "vol_z_threshold": 3.0,
        "rsi_overbought": 80.0,
        "rsi_oversold": 20.0,
        "atr_pct_min": 0.012,
        "vwap_deviation": 0.04,
    },
    "apeusdt": {
        "vol_z_threshold": 2.5,
        "rsi_overbought": 78.0,
        "rsi_oversold": 22.0,
        "atr_pct_min": 0.009,
        "vwap_deviation": 0.03,
    },
    "ldousdt": {
        "vol_z_threshold": 2.5,
        "rsi_overbought": 76.0,
        "rsi_oversold": 24.0,
        "atr_pct_min": 0.008,
        "vwap_deviation": 0.03,
    },
    "crvusdt": {
        "vol_z_threshold": 2.5,
        "rsi_overbought": 76.0,
        "rsi_oversold": 24.0,
        "atr_pct_min": 0.008,
        "vwap_deviation": 0.03,
    },
    "minausdt": {
        "vol_z_threshold": 2.5,
        "rsi_overbought": 75.0,
        "rsi_oversold": 25.0,
        "atr_pct_min": 0.008,
        "vwap_deviation": 0.03,
    },
    "ftmusdt": {
        "vol_z_threshold": 2.5,
        "rsi_overbought": 77.0,
        "rsi_oversold": 23.0,
        "atr_pct_min": 0.009,
        "vwap_deviation": 0.03,
    },
    "algousdt": {
        "vol_z_threshold": 2.5,
        "rsi_overbought": 75.0,
        "rsi_oversold": 25.0,
        "atr_pct_min": 0.008,
        "vwap_deviation": 0.03,
    },
    "axsusdt": {
        "vol_z_threshold": 3.0,
        "rsi_overbought": 78.0,
        "rsi_oversold": 22.0,
        "atr_pct_min": 0.010,
        "vwap_deviation": 0.04,
    },
    "grtusdt": {
        "vol_z_threshold": 3.0,
        "rsi_overbought": 78.0,
        "rsi_oversold": 22.0,
        "atr_pct_min": 0.010,
        "vwap_deviation": 0.04,
    },
    "thetausdt": {
        "vol_z_threshold": 2.5,
        "rsi_overbought": 74.0,
        "rsi_oversold": 26.0,
        "atr_pct_min": 0.008,
        "vwap_deviation": 0.03,
    },
    "chzusdt": {
        "vol_z_threshold": 2.5,
        "rsi_overbought": 74.0,
        "rsi_oversold": 26.0,
        "atr_pct_min": 0.008,
        "vwap_deviation": 0.03,
    },
    "galausdt": {
        "vol_z_threshold": 3.0,
        "rsi_overbought": 80.0,
        "rsi_oversold": 20.0,
        "atr_pct_min": 0.012,
        "vwap_deviation": 0.04,
    },
    "compusdt": {
        "vol_z_threshold": 3.0,
        "rsi_overbought": 74.0,
        "rsi_oversold": 26.0,
        "atr_pct_min": 0.010,
        "vwap_deviation": 0.03,
    },
    "mkrusdt": {
        "vol_z_threshold": 3.0,
        "rsi_overbought": 74.0,
        "rsi_oversold": 26.0,
        "atr_pct_min": 0.010,
        "vwap_deviation": 0.03,
    },
    "snxusdt": {
        "vol_z_threshold": 3.0,
        "rsi_overbought": 74.0,
        "rsi_oversold": 26.0,
        "atr_pct_min": 0.010,
        "vwap_deviation": 0.03,
    },
    "icpusdt": {
        "vol_z_threshold": 3.0,
        "rsi_overbought": 76.0,
        "rsi_oversold": 24.0,
        "atr_pct_min": 0.010,
        "vwap_deviation": 0.04,
    },
    "vetusdt": {
        "vol_z_threshold": 3.0,
        "rsi_overbought": 76.0,
        "rsi_oversold": 24.0,
        "atr_pct_min": 0.010,
        "vwap_deviation": 0.04,
    },
    "stxusdt": {
        "vol_z_threshold": 3.0,
        "rsi_overbought": 77.0,
        "rsi_oversold": 23.0,
        "atr_pct_min": 0.010,
        "vwap_deviation": 0.04,
    },
    "eosusdt": {
        "vol_z_threshold": 3.0,
        "rsi_overbought": 75.0,
        "rsi_oversold": 25.0,
        "atr_pct_min": 0.010,
        "vwap_deviation": 0.04,
    },
    "woousdt": {
        "vol_z_threshold": 3.0,
        "rsi_overbought": 78.0,
        "rsi_oversold": 22.0,
        "atr_pct_min": 0.012,
        "vwap_deviation": 0.04,
    },
    "luncusdt": {
        "vol_z_threshold": 3.5,
        "rsi_overbought": 85.0,
        "rsi_oversold": 15.0,
        "atr_pct_min": 0.015,
        "vwap_deviation": 0.05,
    },
    "iotausdt": {
        "vol_z_threshold": 3.0,
        "rsi_overbought": 75.0,
        "rsi_oversold": 25.0,
        "atr_pct_min": 0.010,
        "vwap_deviation": 0.04,
    },
    "flowusdt": {
        "vol_z_threshold": 3.0,
        "rsi_overbought": 75.0,
        "rsi_oversold": 25.0,
        "atr_pct_min": 0.010,
        "vwap_deviation": 0.04,
    },
    "imxusdt": {
        "vol_z_threshold": 3.0,
        "rsi_overbought": 77.0,
        "rsi_oversold": 23.0,
        "atr_pct_min": 0.010,
        "vwap_deviation": 0.04,
    },
    "xtzusdt": {
        "vol_z_threshold": 3.0,
        "rsi_overbought": 75.0,
        "rsi_oversold": 25.0,
        "atr_pct_min": 0.010,
        "vwap_deviation": 0.04,
    },
    "cfxusdt": {
        "vol_z_threshold": 3.5,
        "rsi_overbought": 80.0,
        "rsi_oversold": 20.0,
        "atr_pct_min": 0.012,
        "vwap_deviation": 0.05,
    },
    "maskusdt": {
        "vol_z_threshold": 3.5,
        "rsi_overbought": 80.0,
        "rsi_oversold": 20.0,
        "atr_pct_min": 0.012,
        "vwap_deviation": 0.05,
    },
    "gmxusdt": {
        "vol_z_threshold": 3.0,
        "rsi_overbought": 78.0,
        "rsi_oversold": 22.0,
        "atr_pct_min": 0.010,
        "vwap_deviation": 0.04,
    },
    "fxsusdt": {
        "vol_z_threshold": 3.0,
        "rsi_overbought": 74.0,
        "rsi_oversold": 26.0,
        "atr_pct_min": 0.010,
        "vwap_deviation": 0.04,
    },
    "cakeusdt": {
        "vol_z_threshold": 3.0,
        "rsi_overbought": 76.0,
        "rsi_oversold": 24.0,
        "atr_pct_min": 0.010,
        "vwap_deviation": 0.04,
    },
    "kavausdt": {
        "vol_z_threshold": 3.0,
        "rsi_overbought": 76.0,
        "rsi_oversold": 24.0,
        "atr_pct_min": 0.010,
        "vwap_deviation": 0.04,
    },
    "blzusdt": {
        "vol_z_threshold": 3.5,
        "rsi_overbought": 82.0,
        "rsi_oversold": 18.0,
        "atr_pct_min": 0.015,
        "vwap_deviation": 0.05,
    },
    "sushiusdt": {
        "vol_z_threshold": 3.0,
        "rsi_overbought": 75.0,
        "rsi_oversold": 25.0,
        "atr_pct_min": 0.010,
        "vwap_deviation": 0.04,
    },
    "runeusdt": {
        "vol_z_threshold": 3.0,
        "rsi_overbought": 78.0,
        "rsi_oversold": 22.0,
        "atr_pct_min": 0.012,
        "vwap_deviation": 0.04,
    },
    "ksmusdt": {
        "vol_z_threshold": 3.0,
        "rsi_overbought": 78.0,
        "rsi_oversold": 22.0,
        "atr_pct_min": 0.012,
        "vwap_deviation": 0.04,
    },
    "wavesusdt": {
        "vol_z_threshold": 3.0,
        "rsi_overbought": 80.0,
        "rsi_oversold": 20.0,
        "atr_pct_min": 0.012,
        "vwap_deviation": 0.04,
    },
    "fetusdt": {
        "vol_z_threshold": 3.5,
        "rsi_overbought": 82.0,
        "rsi_oversold": 18.0,
        "atr_pct_min": 0.015,
        "vwap_deviation": 0.05,
    },
    "oceanusdt": {
        "vol_z_threshold": 3.5,
        "rsi_overbought": 82.0,
        "rsi_oversold": 18.0,
        "atr_pct_min": 0.015,
        "vwap_deviation": 0.05,
    },
    "cocosusdt": {
        "vol_z_threshold": 4.0,
        "rsi_overbought": 85.0,
        "rsi_oversold": 15.0,
        "atr_pct_min": 0.020,
        "vwap_deviation": 0.05,
    },
    "leverusdt": {
        "vol_z_threshold": 4.0,
        "rsi_overbought": 85.0,
        "rsi_oversold": 15.0,
        "atr_pct_min": 0.020,
        "vwap_deviation": 0.05,
    },
    "idusdt": {
        "vol_z_threshold": 4.0,
        "rsi_overbought": 85.0,
        "rsi_oversold": 15.0,
        "atr_pct_min": 0.020,
        "vwap_deviation": 0.05,
    },
    "ssvusdt": {
        "vol_z_threshold": 3.5,
        "rsi_overbought": 80.0,
        "rsi_oversold": 20.0,
        "atr_pct_min": 0.015,
        "vwap_deviation": 0.05,
    },
    "linausdt": {
        "vol_z_threshold": 3.5,
        "rsi_overbought": 80.0,
        "rsi_oversold": 20.0,
        "atr_pct_min": 0.015,
        "vwap_deviation": 0.05,
    },
    "phbusdt": {
        "vol_z_threshold": 4.0,
        "rsi_overbought": 85.0,
        "rsi_oversold": 15.0,
        "atr_pct_min": 0.020,
        "vwap_deviation": 0.05,
    },
    "rdntusdt": {
        "vol_z_threshold": 3.5,
        "rsi_overbought": 82.0,
        "rsi_oversold": 18.0,
        "atr_pct_min": 0.015,
        "vwap_deviation": 0.05,
    },
    "stblusdt": {
        "vol_z_threshold": 4.0,
        "rsi_overbought": 85.0,
        "rsi_oversold": 15.0,
        "atr_pct_min": 0.020,
        "vwap_deviation": 0.05,
    },
    "tutusdt": {
        "vol_z_threshold": 4.0,
        "rsi_overbought": 85.0,
        "rsi_oversold": 15.0,
        "atr_pct_min": 0.020,
        "vwap_deviation": 0.05,
    },
    "wlfiusdt": {
        "vol_z_threshold": 4.0,
        "rsi_overbought": 85.0,
        "rsi_oversold": 15.0,
        "atr_pct_min": 0.020,
        "vwap_deviation": 0.05,
    },
    "penguusdt": {
        "vol_z_threshold": 4.0,
        "rsi_overbought": 85.0,
        "rsi_oversold": 15.0,
        "atr_pct_min": 0.020,
        "vwap_deviation": 0.05,
    },
    "pumpusdt": {
        "vol_z_threshold": 4.0,
        "rsi_overbought": 85.0,
        "rsi_oversold": 15.0,
        "atr_pct_min": 0.020,
        "vwap_deviation": 0.05,
    },
    "enausdt": {
        "vol_z_threshold": 4.0,
        "rsi_overbought": 85.0,
        "rsi_oversold": 15.0,
        "atr_pct_min": 0.020,
        "vwap_deviation": 0.05,
    },
    "arpausdt": {
        "vol_z_threshold": 3.5,
        "rsi_overbought": 82.0,
        "rsi_oversold": 18.0,
        "atr_pct_min": 0.015,
        "vwap_deviation": 0.05,
    },
    "hookusdt": {
        "vol_z_threshold": 3.5,
        "rsi_overbought": 82.0,
        "rsi_oversold": 18.0,
        "atr_pct_min": 0.015,
        "vwap_deviation": 0.05,
    },
    "magicusdt": {
        "vol_z_threshold": 3.5,
        "rsi_overbought": 82.0,
        "rsi_oversold": 18.0,
        "atr_pct_min": 0.015,
        "vwap_deviation": 0.05,
    },
    "c98usdt": {
        "vol_z_threshold": 3.5,
        "rsi_overbought": 80.0,
        "rsi_oversold": 20.0,
        "atr_pct_min": 0.015,
        "vwap_deviation": 0.05,
    },
    "zilusdt": {
        "vol_z_threshold": 3.5,
        "rsi_overbought": 80.0,
        "rsi_oversold": 20.0,
        "atr_pct_min": 0.015,
        "vwap_deviation": 0.05,
    },
    "batusdt": {
        "vol_z_threshold": 3.0,
        "rsi_overbought": 78.0,
        "rsi_oversold": 22.0,
        "atr_pct_min": 0.012,
        "vwap_deviation": 0.04,
    },
    "sfpusdt": {
        "vol_z_threshold": 3.5,
        "rsi_overbought": 80.0,
        "rsi_oversold": 20.0,
        "atr_pct_min": 0.015,
        "vwap_deviation": 0.05,
    },
    "aliceusdt": {
        "vol_z_threshold": 3.5,
        "rsi_overbought": 78.0,
        "rsi_oversold": 22.0,
        "atr_pct_min": 0.015,
        "vwap_deviation": 0.05,
    },
    "blurusdt": {
        "vol_z_threshold": 3.5,
        "rsi_overbought": 80.0,
        "rsi_oversold": 20.0,
        "atr_pct_min": 0.015,
        "vwap_deviation": 0.05,
    },
    "tlmusdt": {
        "vol_z_threshold": 3.5,
        "rsi_overbought": 78.0,
        "rsi_oversold": 22.0,
        "atr_pct_min": 0.015,
        "vwap_deviation": 0.05,
    },
    "yfiusdt": {
        "vol_z_threshold": 3.0,
        "rsi_overbought": 74.0,
        "rsi_oversold": 26.0,
        "atr_pct_min": 0.010,
        "vwap_deviation": 0.04,
    },
    "ankrusdt": {
        "vol_z_threshold": 3.5,
        "rsi_overbought": 78.0,
        "rsi_oversold": 22.0,
        "atr_pct_min": 0.015,
        "vwap_deviation": 0.05,
    },
    "klayusdt": {
        "vol_z_threshold": 3.5,
        "rsi_overbought": 78.0,
        "rsi_oversold": 22.0,
        "atr_pct_min": 0.015,
        "vwap_deviation": 0.05,
    },
    "neousdt": {
        "vol_z_threshold": 3.0,
        "rsi_overbought": 76.0,
        "rsi_oversold": 24.0,
        "atr_pct_min": 0.010,
        "vwap_deviation": 0.04,
    },
}
